services:
  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    depends_on:
      - auth
      - game
    restart: on-failure
    #! frontend dev mode
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 5173
    command: npm run dev
    environment:
      - VITE_GOOGLE_AUTH_CLIENT_ID=${VITE_GOOGLE_AUTH_CLIENT_ID}

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - auth
      - game
    restart: on-failure

  db-init:
    image: db-init
    container_name: db-init
    build: ./scripts/db-init
    volumes:
      - sqlite-data:/data
  auth:
    image: auth
    container_name: auth
    build: ./services/auth
    volumes:
      - ./services/auth:/app
      - /app/node_modules
      - sqlite-data:/data
    depends_on:
      - db-init
    restart: on-failure
  game:
    image: game
    container_name: game
    build: ./services/game
    volumes:
      - ./services/game:/app
      - /app/node_modules
      - sqlite-data:/data
    depends_on:
      - db-init
    restart: on-failure

networks:
  transcendence_net:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind