services:
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - auth
      - game
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - auth
      - game
  auth:
    image: auth
    build: ./services/auth
    volumes:
      - ./services/auth:/app
      - /app/node_modules
      - sqlite-data:/data
  game:
    image: game
    build: ./services/game
    volumes:
      - ./services/game:/app
      - /app/node_modules
      - sqlite-data:/data

networks:
  transcendence_net:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
    driver_opts:
      type: none
      device: sqlite/data
      o: bind
#volumes:
#  auth-app:
#    driver: local
#    driver_opts:
#      type: none
#      device: services/auth
#      o: bind
#  game-app:
#    driver: local
#    driver_opts:
#      type: none
#      device: services/game
#      o: bind