#! ANCHORUS
x-logging:
  &elk
  driver: syslog
  options:
    syslog-address: "tcp://127.0.0.1:8044"
    syslog-format: rfc5424
    tag: "{{.Name}}"
    env: json

services:
  #! INIT SCRIPTS
  db-init:
    image: db-init
    container_name: db-init
    build: ./scripts/db-init
    networks:
      - transcendence_net
    volumes:
      - sqlite-data:/data
  elk-init:
    image: curlimages/curl:7.88.1
    container_name: elk-init
    build: ./scripts/elk-init
    networks:
      - transcendence_net
    depends_on:
      - logstash

  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    networks:
      - transcendence_net
    depends_on:
      elk-init:
        condition: service_completed_successfully
    restart: on-failure
    #TODO: redirect logs to elk

    #* frontend dev mode
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 5173
    command: npm run dev
    environment:
      - VITE_GOOGLE_AUTH_CLIENT_ID=${VITE_GOOGLE_AUTH_CLIENT_ID}

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    networks:
      - transcendence_net
    ports:
      - "8443:443"
    depends_on:
      elk-init:
        condition: service_completed_successfully
      frontend:
        condition: service_started
      auth:
        condition: service_started
      game:
        condition: service_started
    restart: on-failure
    logging: *elk

  auth:
    image: auth
    container_name: auth
    build: ./services/auth
    restart: on-failure
    networks:
      - transcendence_net
    volumes:
      - ./services/auth:/app
      - /app/node_modules
      - sqlite-data:/data
    depends_on:
      elk-init:
        condition: service_completed_successfully
      db-init:
        condition: service_completed_successfully
    logging: *elk
    
  game:
    image: game
    container_name: game
    build: ./services/game
    restart: on-failure
    networks:
      - transcendence_net
    volumes:
      - ./services/game:/app
      - /app/node_modules
      - sqlite-data:/data
    depends_on:
      elk-init:
        condition: service_completed_successfully
      db-init:
        condition: service_completed_successfully
    logging: *elk
    


  #! ELK STACK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - transcendence_net
    ports:
      - 9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 5s
      retries: 10
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - transcendence_net
    ports:
      - "8044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - transcendence_net
    ports:
      - "8601:5601"
    depends_on:
      elk-init:
        condition: service_completed_successfully

networks:
  transcendence_net:
    driver: bridge

volumes:
  sqlite-data:
  elastic-data: