services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "8200:9200"
      - "8300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 5s
      retries: 10

  logstash:
    container_name: logstash
    build: ./logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "8044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "8601:5601"
    depends_on:
      logstash:
        condition: service_healthy

  elk-writer:
    build:
      context: ./elk-writer
    container_name: elk-writer
    depends_on:
      logstash:
        condition: service_healthy
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "tcp://logstash:8044"
    #    tag: "el-writer-logs"
