services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "8200:9200"
      - "8300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 5s
      retries: 10

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.10.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "8044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: setup
    entrypoint: ["/bin/bash", "-c", "echo 'Waiting for Elasticsearch to be ready...' && sleep 30 && curl -X POST 'http://elasticsearch:9200/_cluster/health?wait_for_status=yellow&timeout=50s'"]
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "8601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy 

  elk-writer:
    build:
      context: ./elk-writer
    container_name: elk-writer
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:8044"
        tag: "elk-writer-logs"